create table task.FX_DEALS(
   ID INT NOT NULL AUTO_INCREMENT,
   DEAL_UNIQUE_ID INT NOT NULL UNIQUE,
   FROM_CURRENCY VARCHAR(3) NOT NULL,
   TO_CURRENCY VARCHAR(3) NOT NULL,
   DEAL_TIME DATE,
   DEAL_AMOUNT INT,
   PRIMARY KEY ( ID )
);